Repository KaiSforza/durak, pull requests merged in 2020-11, with the labels that each got.

#30 Updating vscode stuffs
  .github/workflows/node.js.yml
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  durak.code-workspace
  package.json
  src/deck.ts
  tsconfig.json
Labels: devops

#31 added some fancy github stuff
  .github/PULL_REQUEST_TEMPLATE/pr_template.md
  .github/auto_assign.yml
Labels: devops

#35 Fix comments and jsdoc, remove cardCompareTrump
  src/common.ts
  src/deck.ts
  test/common.test.ts
  test/deck.test.ts
Labels: backend

#36 Faster installs, install before task/launch
  .vscode/bin/install.ps1
  .vscode/bin/install.sh
  .vscode/launch.json
  .vscode/tasks.json
  package.json
Labels: devops

#37 Bypass script errors.
  .vscode/tasks.json
Labels: devops

#38 Use newer versions
  .github/workflows/node.js.yml
  .vscode/launch.json
  package.json
Labels: devops

#41 Added gitlab and gitlab.kaictl.me status badges
  README.md
Labels: devops

#43 Use npm run not npm
  .github/workflows/node.js.yml
  .github/workflows/npm-publish.yml
Labels: devops

#42 added react and webpack, moved rendering of main menu from html to tsx
  index.html
  package.json
  src/app.tsx
  tsconfig.json
  webpack.config.js
Labels: devops, enhancement

#45 Clean up README, add build:tsc for old build
  README.md
  package.json
Labels: devops, documentation

#46 Add deploy step for gitlab
  .gitlab-ci.yml
Labels: devops, gitlab

#47 Use node image for this
  .gitlab-ci.yml
Labels: devops, gitlab

#50 Set .gitlab-ci.yml to enable or configure SAST
  .gitlab-ci.yml
Labels: gitlab

#53 Add minimal dependabot file for gitlab
  .gitlab/dependabot.yml
Labels: devops, gitlab
